version: '3.7'
services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mugisha12!
      POSTGRES_DB: studentMs
    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always

  secondary_postgres:
    container_name: secondary_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mugisha12!
      POSTGRES_DB: classMs
    volumes:
      - ./secondary_postgres-order:/data/postgres
    expose:
      - "5433"
    ports:
      - "5433:5432"
    restart: always

  redis:
    container_name: redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mugisha12!
      POSTGRES_DB: keycloak
      PGDATA: /data/postgres
    volumes:
      - ./postgres-keycloak:/data/postgres



  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: Mugisha12!
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - postgres-keycloak