version: '3.7'
services:
  postgres-class:
    container_name: postgres-class
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mugisha12!
      POSTGRES_DB: classMs
      PGDATA: /data/postgres

    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"

    command: >
      bash -c "
      mkdir -p /var/lib/postgresql/data && 
      chmod -R 0700 /var/lib/postgresql/data && 
      chown -R postgres:postgres /var/lib/postgresql/data && 
      postgres -D /var/lib/postgresql/data -p 5431"

    restart: always


  redis:
    container_name: redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always